import serial
import time

def write_throttled(s):
    ser.write(s)
    time.sleep(100/1000)


ser = serial.Serial('/dev/ttyUSB0', 115200)
print(ser.portstr)

ser.write(b'mqttbroker test.mosquitto.org 8884\r')


# Write CA certificate
write_throttled(b'ssl_ca_cert_start\r')
write_throttled(b'-----BEGIN CERTIFICATE-----\r')
write_throttled(b'MIIEAzCCAuugAwIBAgIUBY1hlCGvdj4NhBXkZ/uLUZNILAwwDQYJKoZIhvcNAQEL\r')
write_throttled(b'BQAwgZAxCzAJBgNVBAYTAkdCMRcwFQYDVQQIDA5Vbml0ZWQgS2luZ2RvbTEOMAwG\r')
write_throttled(b'A1UEBwwFRGVyYnkxEjAQBgNVBAoMCU1vc3F1aXR0bzELMAkGA1UECwwCQ0ExFjAU\r')
write_throttled(b'BgNVBAMMDW1vc3F1aXR0by5vcmcxHzAdBgkqhkiG9w0BCQEWEHJvZ2VyQGF0Y2hv\r')
write_throttled(b'by5vcmcwHhcNMjAwNjA5MTEwNjM5WhcNMzAwNjA3MTEwNjM5WjCBkDELMAkGA1UE\r')
write_throttled(b'BhMCR0IxFzAVBgNVBAgMDlVuaXRlZCBLaW5nZG9tMQ4wDAYDVQQHDAVEZXJieTES\r')
write_throttled(b'MBAGA1UECgwJTW9zcXVpdHRvMQswCQYDVQQLDAJDQTEWMBQGA1UEAwwNbW9zcXVp\r')
write_throttled(b'dHRvLm9yZzEfMB0GCSqGSIb3DQEJARYQcm9nZXJAYXRjaG9vLm9yZzCCASIwDQYJ\r')
write_throttled(b'KoZIhvcNAQEBBQADggEPADCCAQoCggEBAME0HKmIzfTOwkKLT3THHe+ObdizamPg\r')
write_throttled(b'UZmD64Tf3zJdNeYGYn4CEXbyP6fy3tWc8S2boW6dzrH8SdFf9uo320GJA9B7U1FW\r')
write_throttled(b'Te3xda/Lm3JFfaHjkWw7jBwcauQZjpGINHapHRlpiCZsquAthOgxW9SgDgYlGzEA\r')
write_throttled(b's06pkEFiMw+qDfLo/sxFKB6vQlFekMeCymjLCbNwPJyqyhFmPWwio/PDMruBTzPH\r')
write_throttled(b'3cioBnrJWKXc3OjXdLGFJOfj7pP0j/dr2LH72eSvv3PQQFl90CZPFhrCUcRHSSxo\r')
write_throttled(b'E6yjGOdnz7f6PveLIB574kQORwt8ePn0yidrTC1ictikED3nHYhMUOUCAwEAAaNT\r')
write_throttled(b'MFEwHQYDVR0OBBYEFPVV6xBUFPiGKDyo5V3+Hbh4N9YSMB8GA1UdIwQYMBaAFPVV\r')
write_throttled(b'6xBUFPiGKDyo5V3+Hbh4N9YSMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL\r')
write_throttled(b'BQADggEBAGa9kS21N70ThM6/Hj9D7mbVxKLBjVWe2TPsGfbl3rEDfZ+OKRZ2j6AC\r')
write_throttled(b'6r7jb4TZO3dzF2p6dgbrlU71Y/4K0TdzIjRj3cQ3KSm41JvUQ0hZ/c04iGDg/xWf\r')
write_throttled(b'+pp58nfPAYwuerruPNWmlStWAXf0UTqRtg4hQDWBuUFDJTuWuuBvEXudz74eh/wK\r')
write_throttled(b'sMwfu1HFvjy5Z0iMDU8PUDepjVolOCue9ashlS4EB5IECdSR2TItnAIiIwimx839\r')
write_throttled(b'LdUdRudafMu5T5Xma182OC0/u/xRlEm+tvKGGmfFcN0piqVl8OrSPBgIlb+1IKJE\r')
write_throttled(b'm/XriWr/Cq4h/JfB7NTsezVslgkBaoU=\r')
write_throttled(b'-----END CERTIFICATE-----\r')
write_throttled(b'ssl_ca_cert_end\r')


# Write client certificate
write_throttled(b'ssl_client_cert_start\r')
write_throttled(b'-----BEGIN CERTIFICATE-----\r')
write_throttled(b'MIIDgDCCAmigAwIBAgIBADANBgkqhkiG9w0BAQsFADCBkDELMAkGA1UEBhMCR0Ix\r')
write_throttled(b'FzAVBgNVBAgMDlVuaXRlZCBLaW5nZG9tMQ4wDAYDVQQHDAVEZXJieTESMBAGA1UE\r')
write_throttled(b'CgwJTW9zcXVpdHRvMQswCQYDVQQLDAJDQTEWMBQGA1UEAwwNbW9zcXVpdHRvLm9y\r')
write_throttled(b'ZzEfMB0GCSqGSIb3DQEJARYQcm9nZXJAYXRjaG9vLm9yZzAeFw0yMzAzMTMxMTQ5\r')
write_throttled(b'NDJaFw0yMzA2MTExMTQ5NDJaMFoxCzAJBgNVBAYTAkFCMQwwCgYDVQQIDANBQkMx\r')
write_throttled(b'DDAKBgNVBAcMA0FiYzEOMAwGA1UECgwFYWJjZGUxCzAJBgNVBAsMAmZnMRIwEAYD\r')
write_throttled(b'VQQDDAlhYmNkIGVmZ2gwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDV\r')
write_throttled(b'zuKa2xBXVrSQ5s5K02Sb3MBQOqcNe8KofS29o/+cFx+jB+FxS/m53xEvRDW9ugb+\r')
write_throttled(b'R0jcAzrwf60dDwBK3JZsN6nDnYvQTc48huji/15/hSZoATzlHC4195oTpnyNgR8E\r')
write_throttled(b'KUrxjKIAefM/A/v0c2gOGi3ft+0iCxFB0xgpWF7LEQMT3xzHLDuqSnyyQpT4LUMt\r')
write_throttled(b'u7elFV9nbbOIDUeFYOveTZBvXibvc3vAmNHk6VoRSqPCqiecqYsbQmrg6mLuaHll\r')
write_throttled(b'52Db8tXU91RdvffBvz5CRSkFB6vX3dDFx7KEMCsbSKQPCNzeOvM+pg7HWWK2SH1w\r')
write_throttled(b'LPi56g1wvyyqaBjEdnLTAgMBAAGjGjAYMAkGA1UdEwQCMAAwCwYDVR0PBAQDAgXg\r')
write_throttled(b'MA0GCSqGSIb3DQEBCwUAA4IBAQASHLQtrVEn1fSeogyH07U/xWBSYrJ7E0lM4Amk\r')
write_throttled(b'MM5ok4tsvcu2GZqJINJaS0EXYOuli5sl5YtkQV8g4zCqyyjs4kx7JpdAmU7ib67R\r')
write_throttled(b'a60hZ7y7/O9RUUwUM1AX85dMivN/qwYhy6tXRN8fSkIW0fOJT6ubwCCh3BhcBlKK\r')
write_throttled(b'8a8I1qkVukb0JBzdjmKgQf8xnQCr0fMIFCeAuHCpJb+uKO9JBvD843Fz9LspVZDU\r')
write_throttled(b'/sJmaI8QZKF97H0Fuk1y2cyva6tKUn2KBaPhdOUiQ+5EX/Txb8bxic7aON0msGYS\r')
write_throttled(b'h/uJNmBmeh5D9Akx+1zHMdwJNslQ+233cySMtWDIEroqGN2A\r')
write_throttled(b'-----END CERTIFICATE-----\r')
write_throttled(b'ssl_client_cert_end\r')


# Write client key
write_throttled(b'ssl_client_key_start\r')
write_throttled(b'-----BEGIN RSA PRIVATE KEY-----\r')
write_throttled(b'MIIEogIBAAKCAQEA1c7imtsQV1a0kObOStNkm9zAUDqnDXvCqH0tvaP/nBcfowfh\r')
write_throttled(b'cUv5ud8RL0Q1vboG/kdI3AM68H+tHQ8AStyWbDepw52L0E3OPIbo4v9ef4UmaAE8\r')
write_throttled(b'5RwuNfeaE6Z8jYEfBClK8YyiAHnzPwP79HNoDhot37ftIgsRQdMYKVheyxEDE98c\r')
write_throttled(b'xyw7qkp8skKU+C1DLbu3pRVfZ22ziA1HhWDr3k2Qb14m73N7wJjR5OlaEUqjwqon\r')
write_throttled(b'nKmLG0Jq4Opi7mh5Zedg2/LV1PdUXb33wb8+QkUpBQer193QxceyhDArG0ikDwjc\r')
write_throttled(b'3jrzPqYOx1litkh9cCz4ueoNcL8sqmgYxHZy0wIDAQABAoIBABAD4CtzT0ULhJj6\r')
write_throttled(b'AOfP79BQ98LKseqro4gVYFC9MQ9TGBaRJ4ziAQGwOMxOkqv0fEOduVJpl4eeOKxd\r')
write_throttled(b'jEsPPOE8RiYV7fwbZ+BWxqkCMeThZ2AQ/6u1saxvMIZaSSgcTON16FwxiYz5lYPZ\r')
write_throttled(b'24yS/G9Z/KeuUj/jjlZc5olqSidxqppERwApQKVfqKzUe0fGx5vZNyrQQuyEPdIS\r')
write_throttled(b'tGOe9BTCoH2LMoCK5YPnYR5IsDkFKGjj1+vXmNmRlPm2PlfSpZtHtxlRQW4vZFRb\r')
write_throttled(b'PtDtZmkWKuJZB43grcBsC7IxK4T+NlQ1ZQN8eacr7o5QPry154HqH82ayTI8Stxt\r')
write_throttled(b'0XqpqbECgYEA/mnbUDpvX3mDR+i+Smm98hP0nes7hiBl7Gycko0zGBt9ogDJnDaA\r')
write_throttled(b'qT738yjnVeC3/NoycBZ+FtPpO7qh7CJEqoMx5idXv0VayTeMs+sfC3Hw4lm1zQ3y\r')
write_throttled(b'RRyBS0RE/BJY1kU9VMeI7Tcdz1CVRQ/NMovYKBdt2YiyGlnrUazrGosCgYEA1yQ0\r')
write_throttled(b'235iLtBxXcA53mK7EcJH2xfn1qEiq0uZQTvMbZ2lJ/GK/wdOz3CiHtfdlwEznSdY\r')
write_throttled(b'pVcoB0dGEbjc4Kga+PlFzuyzJFuGF7REz9mI7CBZE0aFI1FJfEWg7ZLKZaBkScbj\r')
write_throttled(b'nOcBcHvzYFtzSDTQs5CMAOMD2l2EfOv17MVMOdkCgYBY95+wEJ893fpgvS0+THgW\r')
write_throttled(b'HZBfYRFxuAashNbEEQibF5H5gxj9vbmEdfazW8x6JZlxnMQimlsBlJ1tO7jAIMOu\r')
write_throttled(b'dS6P85Yl1xUGZJyZllFG6VN5dDG1QXlFXdCBB6CwHaJfW9s0uIpTmgCcrOtmOT5i\r')
write_throttled(b'vLCcZIUPm1PdDzDRYQzePQKBgCCe48jYK+jvQBE4AU4/6B90NtL4l/WKLyiL6Ovk\r')
write_throttled(b'NkX0nkMlM68hm4iGin5kuruXugy9F4rSYUZhPzWWsx75PkW7/iK27x63JejYM4rU\r')
write_throttled(b'cBdlfDwY+Dz3qU3HfPQoyrmIDUzGdGKpACXfFXLpytwK7g4b/65uvXnRrjIG0R4a\r')
write_throttled(b'eElZAoGALnnSp3GshtvKn4Fiv0jJXU8B0ReqgC8KPfxKHdv4OfoGO0lyDG9qM6ux\r')
write_throttled(b'AnlXwOFJ/His4IdI0QlGVMaWijQ6qNDks2P+tV/OPH81zPecPcpfhM+h1NWqgoFT\r')
write_throttled(b'+3z5HEK69Z4mzxs9LWTx+zO6nJ445CeSQ4tW3U+86cGDcsTJk18=\r')
write_throttled(b'-----END RSA PRIVATE KEY-----\r')
write_throttled(b'ssl_client_key_end\r')

# Restart ESP
write_throttled(b'restart\r')

ser.close()